"Bot_API": 7920823489:AAH5HPYL1DlCbbfrqd5F692MKX13I2kfekE
"DB_Name": quiz_bot.db

"Start_But": Я ну очень хочу играть эту игру
"Stats_But": Покажи статистику игроков этой игры
"Stop_But": Спасибо, но я больше не проявляю к вашей игре интереса.

"Answer_action": answ